/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "orgate.v:1" *)
module orgate(a, b, c);
  (* src = "orgate.v:2" *)
  input a;
  (* src = "orgate.v:2" *)
  input b;
  (* src = "orgate.v:3" *)
  output c;
  assign c = a |(* src = "orgate.v:4" *)  b;
endmodule
